In [1]:
import numpy as np
import matplotlib.pyplot as plt

import os
import datetime

import IPython
import IPython.display
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

import tqdm as tq
import string
import statistics as stats
import re

from numpy import arange, mean, var, std, array, append, diff, cumsum

import sqlite3

In [2]:
df = pd.read_csv('all_street.csv')

In [5]:
df['Datetime'] = pd.to_datetime(df['Month'], format='%Y.%m')
df['Month_int'] = pd.DatetimeIndex(df['Datetime']).month
df['Year_int'] = pd.DatetimeIndex(df['Datetime']).year

In [8]:
df = df.sort_values(by='Month')

In [101]:
df_grouped = df.groupby(['Month', 'LSOA code']).count()

In [102]:
df_grouped

                   Unnamed: 0  Crime ID  Falls within  LSOA name  Crime type  \
Month   LSOA code
2015-01 E01000001          17        12            17         17          17
        E01000002          17        12            17         17          17
        E01000003           2         1             2          2           2
        E01000005          38        28            38         38          38
        E01000006          10         9            10         10          10
...                       ...       ...           ...        ...         ...
2021-10 W01001954           6         2             6          6           6
        W01001955         265       205           265        265         265
        W01001956           7         6             7          7           7
        W01001957          37        22            37         37          37
        W01001958          16        12            16         16          16

                   Last outcome category  Datetime  Month_int  Year_int
Month   LSOA code
2015-01 E01000001                     12        17         17        17
        E01000002                     12        17         17        17
        E01000003                      1         2          2         2
        E01000005                     28        38         38        38
        E01000006                      9        10         10        10
...                                  ...       ...        ...       ...
2021-10 W01001954                      2         6          6         6
        W01001955                    205       265        265       265
        W01001956                      6         7          7         7
        W01001957                     22        37         37        37
        W01001958                     12        16         16        16

[2761180 rows x 9 columns]

In [103]:
df_grouped2 = df_grouped[['Crime type']]

In [104]:
df_grouped2.reset_index(inplace=True)

In [105]:
months = df['Month'].unique()

In [106]:
lsoa = df['LSOA code'].unique()

In [107]:
lsoa_lst = []
for m in months:
    lst = []
    lst = df_grouped2[df_grouped2['Month'] == m]['LSOA code'].to_list()
    lsoa_lst.append(lst)

In [108]:
df_grouped_copy = df_grouped2.copy()

In [109]:
for ls, mo in zip(lsoa_lst, months):
    diff = set(ls).symmetric_difference(set(lsoa))
    df2 = pd. DataFrame({'LSOA code': list(diff)})
    df2['Month'] = mo
    df2['Crime type'] = 0
    df2 = df2[['Month', 'LSOA code', 'Crime type']]
    df_grouped_copy = pd.concat([df_grouped_copy, df2], axis=0)

In [110]:
df_sort = df_grouped_copy.sort_values(by='Month')

In [111]:
df_sort = df_sort.reset_index()

In [115]:
df_sort = df_sort[['Month', 'LSOA code', 'Crime type']]

In [116]:
df_sort = df_sort.rename(columns= {'Crime type' : 'Sum crimes'})

In [118]:
df_sort.to_csv('crimes_per_month_lsoa.csv')

In [117]:
df_sort

           Month  LSOA code  Sum crimes
0        2015-01  E01000001          17
1        2015-01  E01024185           7
2        2015-01  E01024184           5
3        2015-01  E01024183           6
4        2015-01  E01024182          77
...          ...        ...         ...
2849413  2021-10  E01013928          19
2849414  2021-10  E01013926          19
2849415  2021-10  E01013924          18
2849416  2021-10  E01013961          34
2849417  2021-10  E01006113           0

[2849418 rows x 3 columns]